server:
  port: 25000

spring:
  application:
    name: gulimall-seckill
  redis:
    host: 192.168.123.205
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.123.205:8848
    sentinel:
      transport:
        dashboard: localhost:8088
        port: 8719
  zipkin:
    base-url: http://192.168.123.205:9411/
    discoveryClientEnabled: false
    sender:
      type: web # 设置使用 http 的方式传输数据
  sleuth:
    sampler:
      #采样率值介于 0 到 1 之间，1 则表示全部采集
      probability: 1


  task:
    execution:
      pool:
        core-size: 20 # 核心数量
        max-size: 50  # 最大数量


management:
  endpoints:
    web:
      exposure:
        include: "*"





